## DATA-X (INDENG 190D): HW 2
### Yong-Chan Shin
#### SID: 25421882

---


# Problem 1

In [2]:
# Q1
import numpy as np
a = np.arange(10,20)
b = np.linspace(1,7,10)
a_square = np.square(a)
b_square = np.square(b)
print "a_square:",a_square
print "b_square:",b_square
added_squared_array = a_square+b_square
print "add both the squared arrays:",added_squared_array
total = 0
for index in range(added_squared_array.shape[0]):
    if index%2==0:
        total+=added_squared_array[index]
print "sum of the even elements of the added array:",total
square_root_added_squared_array = np.sqrt(added_squared_array)
print "square root of the added array:",square_root_added_squared_array

a_square: [100 121 144 169 196 225 256 289 324 361]
b_square: [  1.           2.77777778   5.44444444   9.          13.44444444
  18.77777778  25.          32.11111111  40.11111111  49.        ]
add both the squared arrays: [ 101.          123.77777778  149.44444444  178.          209.44444444
  243.77777778  281.          321.11111111  364.11111111  410.        ]
sum of the even elements of the added array: 1105.0
square root of the added array: [ 10.04987562  11.12554618  12.22474721  13.34166406  14.47219556
  15.61338457  16.76305461  17.91957341  19.08169571  20.24845673]


In [3]:
#Q2
m = np.append(a,b).reshape(5,4)
print m

[[ 10.          11.          12.          13.        ]
 [ 14.          15.          16.          17.        ]
 [ 18.          19.           1.           1.66666667]
 [  2.33333333   3.           3.66666667   4.33333333]
 [  5.           5.66666667   6.33333333   7.        ]]


In [4]:
#Q3
m2 = np.append(m[:,2],m[:,3]).reshape(5,2)
print m2

[[ 12.          16.        ]
 [  1.           3.66666667]
 [  6.33333333  13.        ]
 [ 17.           1.66666667]
 [  4.33333333   7.        ]]


In [5]:
#Q4
m3 = np.dot(m2.T,m)
print m3

[[ 309.33333333  342.88888889  256.11111111  287.55555556]
 [ 484.22222222  522.66666667  314.11111111  348.22222222]]


In [6]:
#Q5
m3 = np.around(m3,decimals=2)
print m3

[[ 309.33  342.89  256.11  287.56]
 [ 484.22  522.67  314.11  348.22]]


In [7]:
#Q6
m3_original_shape = m3.shape
m3 = m3.reshape(1,m3.shape[0]*m3.shape[1])
m3 = np.sort(m3)
m3 = np.fliplr(m3)
m3 = m3.reshape(m3_original_shape[0],m3_original_shape[1])
print m3

[[ 522.67  484.22  348.22  342.89]
 [ 314.11  309.33  287.56  256.11]]
